import Head from 'next/head'
import React, { useEffect } from 'react'

import { useRouter } from 'next/router';
import LightBeam from '../components/LightBeam/LightBeam';

const MainLayout = ({children}) => {
  const router = useRouter();

  const handleExitAnimation = () => {
    alert('değişiyor')
  };

  useEffect(() => {
    const handleRouteChange = () => {
      handleExitAnimation();
    };

    router.events.on('routeChangeStart', handleRouteChange);

    return () => {
      router.events.off('routeChangeStart', handleRouteChange);
    };
  }, []);

  return (
    < >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LightBeam/>
        {children}
      </main>
    </>
  )
}

export default MainLayout